trigger:
  tags:
    include:
    - '*'
  
pr:
  branches:
    include:
    - develop
    - master
    - main

resources:
  repositories:
  - repository: templates
    endpoint: thenoobsbr
    type: github
    name: TheNoobsBr/Azure-Templates
    ref: refs/heads/main

variables:
- template: variables.yml

stages:
- template: templates/gitflow_calculate_version.yml@templates
  parameters:
    pool: 'Self-hosted'
- template: templates/library_build.yml@templates
  parameters:
    pool: 'Self-hosted'
- template: templates/library_deploy.yml@templates
  parameters:
    pool: 'Self-hosted'
    nuget_api_key: $(NUGET_API_KEY)
  